<?php
/**
 * Default Russian Lexicon Entries for Tickets
 */

include_once('setting.inc.php');

$_lang['tickets'] = 'Тикеты';
$_lang['comments'] = 'Комментарии';
$_lang['threads'] = 'Ветви комментариев';
$_lang['authors'] = 'Авторы';
$_lang['tickets_section'] = 'Раздел с тикетами';
$_lang['ticket'] = 'Тикет';
$_lang['ticket_all'] = 'Все';
$_lang['ticket_menu_desc'] = 'Управление комментариями и не только.';
$_lang['comments_all'] = 'Все комментарии';

$_lang['tickets_section_create_here'] = 'Раздел с тикетами';
$_lang['tickets_section_new'] = 'Новый раздел тикетов';
$_lang['tickets_section_management'] = 'Управление тикетами';
$_lang['tickets_section_duplicate'] = 'Копировать секцию';
$_lang['tickets_section_unpublish'] = 'Снять с публикации';
$_lang['tickets_section_publish'] = 'Опубликовать секцию';
$_lang['tickets_section_undelete'] = 'Восстановить секцию';
$_lang['tickets_section_delete'] = 'Удалить секцию';
$_lang['tickets_section_view'] = 'Просмотреть на сайте';

$_lang['tickets_section_settings'] = 'Настройки раздела';
$_lang['tickets_section_tab_main'] = 'Основные';

$_lang['tickets_section_tab_tickets'] = 'Дочерние тикеты';
$_lang['tickets_section_tab_tickets_intro'] = 'Все настройки на этой странице действуют только на новые тикеты.';
$_lang['tickets_section_settings_template'] = 'Шаблон дочерних документов';
$_lang['tickets_section_settings_template_desc'] = 'Выберите шаблон, который будет присвоен всем новым тикетам, создаваемым в этой секции. Если шаблон не указан - он будет взят из системной настройки <b>tickets.default_template</b>.';
$_lang['tickets_section_settings_uri'] = 'Формирование URI';
$_lang['tickets_section_settings_uri_desc'] = 'Вы можете использовать <b>%y</b> - год двумя цифрами, <b>%m</b> - месяц, <b>%d</b> - день, <b>%alias</b> - псевдоним, <b>%id</b> - идентификатор и <b>%ext</b> - расширение документа.';
$_lang['tickets_section_settings_show_in_tree'] = 'Показывать в дереве';
$_lang['tickets_section_settings_show_in_tree_desc'] = 'По умолчанию тикеты не показываются в дереве документов, чтобы снизить нагрузку на админку, но вы можете включить это для новых документов.';
$_lang['tickets_section_settings_hidemenu'] = 'Скрыть в меню';
$_lang['tickets_section_settings_hidemenu_desc'] = 'Вы можете указать настройку отображения новых тикетов в меню.';
$_lang['tickets_section_settings_disable_jevix'] = 'Отключить Jevix';
$_lang['tickets_section_settings_disable_jevix_desc'] = 'По умолчанию, в целях безопасности, все тикеты обрабатываются сниппетом Jevix. Вы можете отключить эту обработку для новых тикетов текущего раздела.';
$_lang['tickets_section_settings_process_tags'] = 'Выполнять теги MODX';
$_lang['tickets_section_settings_process_tags_desc'] = 'По умолчанию, в целях безопасности, в тикетах не выполняются теги MODX. Вы можете включить их выполнение в новых тикетах текущего раздела.';

$_lang['tickets_section_tab_ratings'] = 'Рейтинги';
$_lang['tickets_section_tab_ratings_intro'] = 'Укажите очки рейтинга для разных действий пользователей в этом разделе.';
$_lang['tickets_section_rating_ticket'] = 'Тикеты';
$_lang['tickets_section_rating_ticket_desc'] = 'Очки рейтинга за создание тикета в этом разделе.';
$_lang['tickets_section_rating_comment'] = 'Комментарии';
$_lang['tickets_section_rating_comment_desc'] = 'Очки рейтинга за комментирование тикетов этого раздела.';
$_lang['tickets_section_rating_view'] = 'Просмотры';
$_lang['tickets_section_rating_view_desc'] = 'Очки за просмотр тикетов в этом разделе.';
$_lang['tickets_section_rating_vote_ticket'] = 'Голос за тикет';
$_lang['tickets_section_rating_vote_ticket_desc'] = 'Очки рейтинга автору тикета за каждое голосование. Отрицательные голоса отнимают рейтинг.';
$_lang['tickets_section_rating_vote_comment'] = 'Голос за комментарий';
$_lang['tickets_section_rating_vote_comment_desc'] = 'Очки рейтинга автору комментария за каждое голосование. Отрицательные голоса отнимают рейтинг.';
$_lang['tickets_section_rating_star_ticket'] = 'Тикет в избранном';
$_lang['tickets_section_rating_star_ticket_desc'] = 'Очки рейтинга автору тикета за каждое добавление в избранное.';
$_lang['tickets_section_rating_star_comment'] = 'Коммент в избранном';
$_lang['tickets_section_rating_star_comment_desc'] = 'Очки рейтинга автору комментария за каждое добавление в избранное.';

$_lang['tickets_section_notify'] = 'Уведомлять о новых тикетах';
$_lang['tickets_section_subscribed'] = 'Вы подписались на уведомления о новых тикетах в этой секции.';
$_lang['tickets_section_unsubscribed'] = 'Вы больше не будете получать уведомления о тикетах из этой секции.';
$_lang['tickets_section_email_subscription'] = 'Новый тикет в секции "[[+section.pagetitle]]"';

$_lang['ticket_create_here'] = 'Создать тикет';

$_lang['ticket_no_comments'] = 'На этой странице еще нет комментариев. Вы можете написать первый.';
$_lang['tickets_message_close_all'] = 'закрыть все';
$_lang['err_no_jevix'] = 'Для работы необходим сниппет Jevix. Вы должны установить его из репозитория MODX.';
$_lang['tickets_err_unknown'] = 'Произошла неизвестная ошибка.';
$_lang['ticket_err_id'] = 'Тикет с указанным id = [[+id]] не найден.';
$_lang['ticket_err_wrong_user'] = 'Вы пытаетесь обновить тикет, который вам не принадлежит.';
$_lang['ticket_err_no_auth'] = 'Вы должны авторизоваться, чтобы создать тикет.';
$_lang['ticket_err_wrong_parent'] = 'Указан неверный раздел для тикета.';
$_lang['ticket_err_wrong_resource'] = 'Указан неверный тикет.';
$_lang['ticket_err_wrong_thread'] = 'Указана неверная ветвь комментариев.';
$_lang['ticket_err_wrong_section'] = 'Указана неверная секция тикетов.';
$_lang['ticket_err_access_denied'] = 'Доступ запрещен.';
$_lang['ticket_err_form'] = 'В форме содержатся ошибки. Пожалуйста, исправьте их.';
$_lang['ticket_err_deleted_comment'] = 'Вы пытаетесь отредактировать удалённый комментарий.';
$_lang['ticket_err_unpublished_comment'] = 'Этот комментарий еще не был опубликован.';
$_lang['ticket_err_ticket'] = 'Указанный тикет не существует.';
$_lang['ticket_err_vote_own'] = 'Вы не можете голосовать за свой тикет.';
$_lang['ticket_err_vote_already'] = 'Вы уже голосовали за этот тикет.';
$_lang['ticket_err_empty'] = 'Вы забыли написать текст тикета.';
$_lang['ticket_err_publish'] = 'Вам запрещено публиковать тикеты.';
$_lang['ticket_err_cut'] = 'Длина текста [[+length]] символов. Вы должны указать тег &lt;cut/&gt, если текст больше [[+max_cut]] символов.';
$_lang['ticket_unpublished_comment'] = 'Ваш комментарий будет опубликован после проверки.';
$_lang['permission_denied'] = 'У вас недостаточно прав для этого действия.';
$_lang['field_required'] = 'Это поле обязательно.';
$_lang['ticket_clear'] = 'Очистить';

$_lang['ticket_comments_intro'] = 'Здесь собраны комментарии со всего сайта.';
$_lang['ticket_comment_deleted_text'] = 'Комментарий был удален.';
$_lang['ticket_comment_remove_confirm'] = 'Вы уверены, что хотите окончательно удалить <b>ветвь комментариев</b>, начиная с этого? Эта операция необратима!';

$_lang['ticket_comment_name'] = 'Автор';
$_lang['ticket_comment_text'] = 'Комментарий';
$_lang['ticket_comment_createdon'] = 'Написан';
$_lang['ticket_comment_editedon'] = 'Изменен';
$_lang['ticket_comment_deletedon'] = 'Удалён';
$_lang['ticket_comment_parent'] = 'Родитель';
$_lang['ticket_comment_thread'] = 'Ветка';
$_lang['ticket_comment_email'] = 'Email';
$_lang['ticket_comment_view'] = 'Открыть комментарий на сайте';
$_lang['ticket_comment_reply'] = 'ответить';
$_lang['ticket_comment_edit'] = 'изменить';
$_lang['ticket_comment_create'] = 'Написать комментарий';
$_lang['ticket_comment_preview'] = 'Предпросмотр';
$_lang['ticket_comment_save'] = 'Написать';
$_lang['ticket_comment_was_edited'] = 'Комментарий был изменён';
$_lang['ticket_comment_guest'] = 'Гость';
$_lang['ticket_comment_deleted'] = 'Удалён';
$_lang['ticket_comment_captcha'] = 'Введите сумму [[+a]] + [[+b]]';
$_lang['ticket_comment_notify'] = 'Уведомлять о новых комментариях';
$_lang['ticket_comment_err_id'] = 'Комментарий с указанным id = [[+id]] не найден.';
$_lang['ticket_comment_err_no_auth'] = 'Вы должны авторизоваться, чтобы оставлять комментарии.';
$_lang['ticket_comment_err_wrong_user'] = 'Вы пытаетесь обновить комментарий, который вам не принадлежит.';
$_lang['ticket_comment_err_no_time'] = 'Время для редактирования истекло.';
$_lang['ticket_comment_err_has_replies'] = 'У этого комментария уже есть ответы, поэтому, вы не можете его менять.';
$_lang['ticket_comment_err_parent'] = 'Комментарий, на который вы отвечаете не существует.';
$_lang['ticket_comment_err_comment'] = 'Указанный комментарий не существует.';
$_lang['ticket_comment_err_vote_own'] = 'Вы не можете голосовать за свой комментарий.';
$_lang['ticket_comment_err_vote_already'] = 'Вы уже голосовали за этот комментарий.';
$_lang['ticket_comment_err_wrong_guest_ip'] = 'Вы не авторизованы и ваш ip не совпадает с ip автора этого комментария.';
$_lang['ticket_comment_err_empty'] = 'Вы забыли написать комментарий.';
$_lang['ticket_comment_err_email'] = 'Вы указали неверный email.';
$_lang['ticket_comment_err_guest_edit'] = 'Вам запрещено редактировать комментарии.';
$_lang['ticket_comment_err_captcha'] = 'Указан неверный код защиты от спама.';
$_lang['ticket_comment_err_no_email'] = 'Вам нужно указать email в настройках вашего аккаунта.';

$_lang['ticket_authors_intro'] = 'В этом разделе собраны профили авторов с рейтингами. Настройки для подсчёта указываются раздельно у каждой секции.<br/>Вы видите сколько тикетов, комментариев и просмотров сделал автор, а также сколько добавили в избранное и проголосовали за них другие пользователи.';
$_lang['ticket_authors_rebuild'] = 'Обновление рейтингов';
$_lang['ticket_authors_rebuild_confirm'] = 'Вы действительно хотите перестроить рейтинги всех авторов сайта? Эта операция может занять много времени.';
$_lang['ticket_authors_rebuild_wait'] = 'Обрабатываю профили авторов...';
$_lang['ticket_authors_rebuild_wait_ext'] = 'Обработано: [[+processed]] из [[+total]].';
$_lang['ticket_author_createdon'] = 'Был создан';
$_lang['ticket_author_visitedon'] = 'Заходил';
$_lang['ticket_author_rating'] = 'Рейтинг';
$_lang['ticket_author_tickets'] = 'Тикеты';
$_lang['ticket_author_comments'] = 'Комментарии';
$_lang['ticket_author_views'] = 'Просмотры';
$_lang['ticket_author_stars'] = 'Избранное';
$_lang['ticket_author_stars_tickets'] = 'Избранные тикеты';
$_lang['ticket_author_stars_comments'] = 'Избранные комменты';
$_lang['ticket_author_votes_tickets'] = 'Рейтинг тикетов';
$_lang['ticket_author_votes_comments'] = 'Рейтинг комментариев';
$_lang['ticket_author_votes_tickets_up'] = 'Голоса за тикеты';
$_lang['ticket_author_votes_tickets_down'] = 'Голоса против тикетов';
$_lang['ticket_author_votes_comments_up'] = 'Голоса за комменты';
$_lang['ticket_author_votes_comments_down'] = 'Голоса против комментов';
$_lang['ticket_author_rating_desc'] = 'За / Против';
$_lang['ticket_author_stars_desc'] = 'Тикеты / Комментарии';

$_lang['ticket_tickets_intro'] = 'Здесь собраны тикеты со всего сайта.';
$_lang['ticket_publishedon'] = 'Опубликован';
$_lang['ticket_pagetitle'] = 'Заголовок';
$_lang['ticket_parent'] = 'Секция';
$_lang['ticket_author'] = 'Автор';
$_lang['ticket_delete'] = 'Удалить тикет';
$_lang['ticket_delete_text'] = 'Вы уверены, что хотите удалить этот тикет?';
$_lang['ticket_create'] = 'Создать тикет';
$_lang['ticket_disable_jevix'] = 'Отключить Jevix';
$_lang['ticket_disable_jevix_help'] = 'Выводить контент страницы без фильтрации сниппетом Jevix. <b>Очень опасно</b>, так как любой пользователь, создающий страницу, сможет атаковать ваш сайт (XSS, LFI и т.п.)';
$_lang['ticket_process_tags'] = 'Выполнять теги MODX';
$_lang['ticket_process_tags_help'] = 'По умолчанию, теги в квадратных скобках выводятся как есть, без обработки парсером. Если включите, на этой странице будут запускаться сниппеты, чанки и т.д.';
$_lang['ticket_private'] = 'Закрытый тикет';
$_lang['ticket_private_help'] = 'Если включено, пользователю требуется разрешение "ticket_view_private" для просмотра этого тикета.';
$_lang['ticket_show_in_tree'] = 'Показывать в дереве';
$_lang['ticket_show_in_tree_help'] = 'По умолчанию, тикеты не показываются в дереве ресурсов MODX, чтобы не нагружать его.';
$_lang['ticket_createdon'] = 'Создан';
$_lang['ticket_publishedon'] = 'Опубликован';
$_lang['ticket_content'] = 'Содержимое';
$_lang['ticket_publish'] = 'Опубликовать';
$_lang['ticket_preview'] = 'Предпросмотр';
$_lang['ticket_comments'] = 'Комментарии';
$_lang['ticket_actions'] = 'Действия';
$_lang['ticket_save'] = 'Сохранить';
$_lang['ticket_draft'] = 'В черновики';
$_lang['ticket_open'] = 'Открыть';
$_lang['ticket_read_more'] = 'Читать дальше';
$_lang['ticket_saved'] = 'Сохранено!';

$_lang['ticket_threads_intro'] = 'Ветки комментариев. Как правило, одна ветка - это комментарии одной страницы.';
$_lang['ticket_thread'] = 'Ветка комментариев';
$_lang['ticket_thread_name'] = 'Имя ветки';
$_lang['ticket_thread_createdon'] = 'Создана';
$_lang['ticket_thread_editedon'] = 'Изменена';
$_lang['ticket_thread_deletedon'] = 'Удалёна';
$_lang['ticket_thread_comments'] = 'Комментарии';
$_lang['ticket_thread_resource'] = 'Id тикета';
$_lang['ticket_thread_delete'] = 'Отключить ветку';
$_lang['ticket_thread_undelete'] = 'Включить ветку';
$_lang['ticket_thread_close'] = 'Закрыть ветку';
$_lang['ticket_thread_open'] = 'Открыть ветку';
$_lang['ticket_thread_remove'] = 'Удалить с комментариями';
$_lang['ticket_thread_remove_confirm'] = 'Вы дейcтвительно хотите удалить <b>всю</b> ветвь комментариев? Эта операция необратима!';
$_lang['ticket_thread_view'] = 'Просмотреть на сайте';
$_lang['ticket_thread_err_deleted'] = 'Комментирование отключено.';
$_lang['ticket_thread_err_closed'] = 'Добавление новых комментариев запрещено.';
$_lang['ticket_thread_manage_comments'] = 'Управление комментариями';
$_lang['ticket_thread_subscribed'] = 'Вы подписались на уведомления о новых комментариях в этой теме.';
$_lang['ticket_thread_unsubscribed'] = 'Вы больше не будете получать уведомления о комментариях из этой темы.';

$_lang['ticket_date_now'] = 'Только что';
$_lang['ticket_date_today'] = 'Сегодня в';
$_lang['ticket_date_yesterday'] = 'Вчера в';
$_lang['ticket_date_tomorrow'] = 'Завтра в';
$_lang['ticket_date_minutes_back'] = '["[[+minutes]] минута назад","[[+minutes]] минуты назад","[[+minutes]] минут назад"]';
$_lang['ticket_date_minutes_back_less'] = 'меньше минуты назад';
$_lang['ticket_date_hours_back'] = '["[[+hours]] час назад","[[+hours]] часа назад","[[+hours]] часов назад"]';
$_lang['ticket_date_hours_back_less'] = 'меньше часа назад';
$_lang['ticket_date_months'] = '["января","февраля","марта","апреля","мая","июня","июля","августа","сентября","октября","ноября","декабря"]';

$_lang['ticket_like'] = 'Нравится';
$_lang['ticket_dislike'] = 'Не нравится';
$_lang['ticket_refrain'] = 'Посмотреть рейтинг';
$_lang['ticket_rating_total'] = 'Всего';
$_lang['ticket_rating_and'] = 'и';

$_lang['ticket_file_select'] = 'Выберите файлы';
$_lang['ticket_file_delete'] = 'Удалить';
$_lang['ticket_file_restore'] = 'Восстановить';
$_lang['ticket_file_insert'] = 'Вставить ссылку';
$_lang['ticket_err_source_initialize'] = 'Не могу инициализировать хранилище файлов';
$_lang['ticket_err_file_ns'] = 'Не могу обработать указанный файл';
$_lang['ticket_err_file_ext'] = 'Неправильно расширение файла';
$_lang['ticket_err_file_save'] = 'Не могу загрузить файл';
$_lang['ticket_err_file_owner'] = 'Этот файл вам принадлежит не вам';
$_lang['ticket_err_file_exists'] = 'Файл с таким именем или содержимым уже существует: "[[+file]]"';
$_lang['ticket_uploaded_files'] = 'Загруженные файлы';

$_lang['tickets_action_view'] = 'Просмотреть';
$_lang['tickets_action_edit'] = 'Изменить';
$_lang['tickets_action_publish'] = 'Опубликовать';
$_lang['tickets_action_unpublish'] = 'Снять с публикации';
$_lang['tickets_action_delete'] = 'Удалить';
$_lang['tickets_action_undelete'] = 'Восстановить';
$_lang['tickets_action_remove'] = 'Уничтожить';
$_lang['tickets_action_duplicate'] = 'Копировать';
$_lang['tickets_action_open'] = 'Открыть';
$_lang['tickets_action_close'] = 'Закрыть';

$_lang['ticket_comment_email_owner'] = 'Новый комментарий к вашему тикету "[[+pagetitle]]"';
$_lang['ticket_comment_email_reply'] = 'Ответ на ваш комментарий к тикету "[[+pagetitle]]"';
$_lang['ticket_comment_email_subscription'] = 'Новый комментарий в теме "[[+pagetitle]]"';
$_lang['ticket_comment_email_bcc'] = 'Новый комментарий в теме "[[+pagetitle]]"';
$_lang['ticket_comment_email_unpublished_bcc'] = 'Неопубликованный комментарий в теме "[[+pagetitle]]"';
$_lang['ticket_comment_email_unpublished_intro'] = 'Пользователь <b>[[+name]]</b> оставил комментарий в тикете "<a href="[[~[[+resource]]?scheme=`full`]]">[[+pagetitle]]</a>".<br/>Теперь вам нужно проверить его и опубликовать на сайте:';
$_lang['ticket_comment_email_subscription_intro'] = 'Пользователь <b>[[+name]]</b> оставил комментарий в тикете, на который вы подписаны - "<a href="[[~[[+resource]]?scheme=`full`]]">[[+pagetitle]]</a>":';
$_lang['ticket_comment_email_reply_intro'] = 'Пользователь <b>[[+name]]</b> ответил на ваш комментарий к тикету "<a href="[[~[[+resource]]?scheme=`full`]]">[[+pagetitle]]</a>":';
$_lang['ticket_comment_email_reply_text'] = 'Текст комментария:';
$_lang['ticket_comment_email_owner_intro'] = 'Пользователь <b>[[+name]]</b> оставил комментарий к вашему тикету "<a href="[[~[[+resource]]?scheme=`full`]]">[[+pagetitle]]</a>":';
$_lang['ticket_comment_email_bcc_intro'] = 'Пользователь <b>[[+name]]</b> оставил комментарий в тикете "<a href="[[~[[+resource]]?scheme=`full`]]">[[+pagetitle]]</a>":';

$_lang['ticket_email_bcc'] = 'Новый тикет у вас на сайте - "[[+pagetitle]]"';
$_lang['ticket_email_bcc_intro'] = 'Пользователь <b>[[+fullname]]</b> ([[+email]]) создал новый тикет у вас на сайте: <a href="[[~[[+id]]?scheme=`full`]]">[[+pagetitle]]</a>';
$_lang['ticket_email_subscribed_intro'] = 'Пользователь <b>[[+fullname]]</b> опубликовал новый тикет: "<a href="[[~[[+id]]?scheme=`full`]]">[[+pagetitle]]</a>" в секции "<a href="[[~[[+section]]?scheme=`full`]]">[[+section_title]]</a>", на которую вы подписаны.';
$_lang['ticket_email_all_comments'] = 'Все комментарии';
$_lang['ticket_email_view'] = 'Просмотреть';
$_lang['ticket_email_reply'] = 'Ответить';